# Generated by Django 4.1.5 on 2023-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto/'),
        ),
        migrations.AddField(
            model_name='foto',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
